baseurl         = "https://805bluebell.github.io/blog/"
theme           = "hugo-casper-two"
publishDir      = "docs"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Another blog"
  subtitle    = "Flowing thoughts of restless mind"
  copyright   = "© 2019"

  cover       = "img/branches-cold-conifers.jpg"
  description = "Various ideas written with best of wits amassed"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "0pankajkumar"
  fbName = "pankajwillkillu"
  githubName = "805bluebell"

  logo = "hugo-logo.png"
  orgName = "PK"
  orgWebsite = "https://805bluebell.github.io/blog"
  orgDescription = "The one man army"

  showSupport = true

  author = "Pankaj Kumar"
  authorAvatar = "img/profile-pic.jpg"
  authorLocation = "Mumbai, India"
  authorWebsite = "https://805bluebell.github.io/"
  authorDescription = "Aspiring software engineer"

  pageNotFoundTitle = "404 - Oh snap !"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Journey"
  url = "/categories/journey/"
  weight = 100

[[menu.main]]
  name = "Technology"
  url = "/categories/technology/"
  weight = 99

[[menu.main]]
  name = "About Me"
  url = "https://805bluebell.github.io/"
  weight = 95


