baseurl         = "https://805bluebell.github.io/blog/"
theme           = "hugo-casper-two"
publishDir      = "docs"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Hugo Casper Two"
  subtitle    = "Port of Casper 2.x for Hugo"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"

  logo = "hugo-logo.png"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Pankaj Kumar"
  authorAvatar = "img/profile-pic.jpg"
  authorLocation = "Mumbai, India"
  authorWebsite = "https://805bluebell.github.io/"
  authorDescription = "Aspiring software engineer"

  pageNotFoundTitle = "404 - Oh snap !"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Journey"
  url = "/categories/journey/"
  weight = 100

[[menu.main]]
  name = "Technology"
  url = "/categories/technology/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95